

; Common settings (not a real env)
[env_common]
build_flags = 
    -D VERSION=0.1.3
    -I lib/hn

; ------------------------------
; Arduino AVR examples
; ------------------------------

[env:receive]
platform = atmelavr
board = nanoatmega328new
framework = arduino
extends = env_common
build_src_filter =
    +<examples/nano_receive/*.cpp>
    -<*>
build_flags =
    ${env_common.build_flags}
    -D receive_buildflag
    -D OLED_I2C
    -D hn_debug
lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit BusIO
    Adafruit SH110X

[platformio]
; moved [env:stm8] to examples/STM8_sw_unit/STM8S003F3.ini
extra_configs =
    examples/STM8_sw_unit/STM8S003F3.ini
    examples/ATMega32U4_send/ATMega32U4_send.ini
;src_dir = examples/nano_receive
default_envs = stm8