[env:send]
platform = atmelavr
board = sparkfun_promicro16
framework = arduino
extends = env_common
;monitor_speed = 9600
build_src_filter =
    +<examples/ATMega32U4_send/*.cpp>
    -<*>
build_flags =
    ${env_common.build_flags}
    -D send_buildflag