[platformio]
; Treat the current folder (examples/stm8_sw_unit) as the project root
;src_dir = .

[env:stm8]
platform = ststm8
board = stm8s003f3
monitor_filters = time

; Use symlink to share code without duplication or -I flags
lib_deps =
    symlink://../../lib/hn/headers
    symlink://../../lib/print

build_flags =
    -DSTM8
    -DSTM8S003F3_sw_unit_v1
    -D__SDCC__

board_build.f_cpu = 12000000L
upload_protocol = stlinkv2
monitor_port = /dev/ttyUSB0
monitor_speed = 9600