[platformio]
src_dir = src

[env:receive]
platform = atmelavr
board = nanoatmega328new
framework = arduino
; build_src_filter =
;     +<examples/nano_receive/*.cpp>
;     -<*>
build_flags =
    ; ${env_common.build_flags}
    -D receive_buildflag
    -D OLED_I2C
    -D hn_debug
lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit BusIO
    Adafruit SH110X